Intervention/image-driver-vips

src/Modifiers/ResizeModifier.php, src/Modifiers/ScaleDownModifier.php, src/Modifiers/ScaleModifier.php, tests/Unit/Modifiers/ScaleDownModifierTest.php, tests/Unit/Modifiers/ScaleModifierTest.php
- Added scale modifier
- Added test
=> Added scale modifier

src/Modifiers/PlaceModifier.php, tests/Unit/Modifiers/PlaceModifierTest.php
=> Place modifier

src/Modifiers/PixelateModifier.php, tests/Unit/Modifiers/PixelateModifierTest.php
- added pixelate modifier
- added test
=> Pixelate modifier

src/Modifiers/RotateModifier.php, tests/Unit/Modifiers/RotateModifierTest.php
=> Rotate modifier

src/Modifiers/TrimModifier.php, tests/Unit/Modifiers/TrimModifierTest.php
=> Trim modifier

src/Analyzers/PixelColorAnalyzer.php, src/Modifiers/BrightnessModifier.php, src/Modifiers/ContrastModifier.php, tests/Unit/Analyzers/PixelColorAnalyzerTest.php, tests/Unit/Modifiers/BrightnessModifierTest.php, tests/Unit/Modifiers/ContrastModifierTest.php
- I was having issues with what `getpoint` was returning, looks like some formats have RGB values higher than 255
- Added test to make sure pixel analyzer works for float
=> Brightness & contrast modifiers

.github/workflows/run-tests.yml, Dockerfile, src/Core.php, src/Decoders/NativeObjectDecoder.php, src/Encoders/AvifEncoder.php, src/Encoders/BmpEncoder.php, src/Encoders/HeicEncoder.php, src/Encoders/Jpeg2000Encoder.php, src/Encoders/JpegEncoder.php, src/Encoders/PngEncoder.php, tests/BaseTestCase.php, tests/Unit/Encoders/AvifEncoderTest.php, tests/Unit/Encoders/BmpEncoderTest.php, tests/Unit/Encoders/HeicEncoderTest.php, tests/Unit/Encoders/Jpeg200EncoderTest.php, tests/Unit/Encoders/JpegEncoderTest.php, tests/Unit/Encoders/PngEncoderTest.php, tests/Unit/Encoders/TiffEncoderTest.php, tests/Unit/Encoders/WebpEncoderTest.php
* resolves #13 
- added test for each encoder
- fixed encoders when necessary
=> #13 - Only use first frame in non-animated formats

readme.md, src/Modifiers/CoverDownModifier.php, src/Modifiers/CoverModifier.php, tests/Unit/Modifiers/CoverDownModifierTest.php, tests/Unit/Modifiers/CoverModifierTest.php
- cover modifier
- cover down modifier
- tests
=> cover and cover down modifiers

src/Core.php, src/Driver.php, src/Modifiers/PixelateModifier.php, src/Modifiers/PlaceModifier.php, tests/Unit/Analyzers/PixelColorsAnalyzerTest.php, tests/Unit/CoreTest.php, tests/Unit/DriverTest.php, tests/Unit/Modifiers/PixelateModifierTest.php, tests/Unit/Modifiers/PlaceModifierTest.php
=> [#24] Fixed core iterrator and affected modifiers

readme.md, src/Core.php, src/Driver.php, src/Modifiers/DrawEllipseModifier.php, tests/Unit/Modifiers/DrawEllipseModifierTest.php
- Added modifier
- Added test on static and animated
=> Implemented `DrawEllipseModifier::class`

src/Modifiers/CropModifier.php, src/Modifiers/FillModifier.php, tests/Unit/Modifiers/CropModifierTest.php, tests/Unit/Modifiers/FillModifierTest.php
=> Fixed number of bands for composite operations

src/Modifiers/CropModifier.php, tests/Unit/Modifiers/CropModifierTest.php
=> Fixed crop position

readme.md, src/Modifiers/DrawPixelModifier.php, tests/Unit/Modifiers/DrawPixelModifierTest.php
```php
use Intervention\Image\Drivers\Vips\Driver as VipsDriver;
use Intervention\Image\ImageManager;
$image = ImageManager::withDriver(VipsDriver::class)
->create(32, 32)
->fill('f00')
->drawPixel(16, 16, '00f');
```
=> Implement DrawPixelModifier::class

readme.md, src/Modifiers/DrawPolygonModifier.php, tests/Unit/Modifiers/DrawPolygonModifierTest.php
=> Implement DrawPolygonModifier::class

readme.md, src/Modifiers/DrawBezierModifier.php, tests/Unit/Modifiers/DrawBezierModifierTest.php
=> Implement DrawBezierModifier::class

readme.md, src/Modifiers/PadModifier.php, tests/Unit/Modifiers/PadModifierTest.php
=> Implement PadModifier::class

src/Modifiers/CoverModifier.php, tests/Unit/Modifiers/CoverDownModifierTest.php, tests/Unit/Modifiers/CoverModifierTest.php
=> Add ability to process animated images for CoverModifier

src/Driver.php, src/LoaderDetector.php, tests/Unit/LoaderDetectorTest.php
=> Improve supported format detection

src/Modifiers/BrightnessModifier.php, src/Modifiers/ColorizeModifier.php, src/Modifiers/ContrastModifier.php, tests/Unit/Analyzers/PixelColorAnalyzerTest.php
=> Replace array constants

src/Driver.php
=> Check driver health by using libvips implementation

src/FontProcessor.php, src/Modifiers/TextModifier.php, src/TrueTypeFont.php, tests/Unit/FontProcessorTest.php
=> Fix TextModifier position bug

src/ColorProcessor.php, tests/Unit/Analyzers/PixelColorAnalyzerTest.php, tests/Unit/ColorProcessorTest.php
=> Fix ArgumentCountError for grayscale images
